# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://legendofmir.github.io
title: 仿韩传奇
email: hellobinge@sina.cn
description: > # "
  仿韩传奇，装备隐藏属性，亿万传奇玩家的经典回忆！
  "

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: 客户端下载
    url: https://www.baidu.com
  - title: 登陆器下载
    url: https://www.baidu.com
  - title: 官方交流群
    url: https://www.baidu.com
